version: "3.0"

services:
  db:
    image: mariadb:10.4.19
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./my-customize.cnf:/etc/mysql/conf.d/my-customize.cnf:ro
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    network_mode: host
  # 启动redis
  demo-redis-server:
    image: redis:5.0.14
    # 设置redis密码
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '6379:6379'
