version: '3.8'

services:
  mysql:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: activiti
      MYSQL_USER: activiti
      MYSQL_PASSWORD: activiti123
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password
    network_mode: "host"