version: "3.0"

networks:
  net:
    name: demo-openresty-config-production-net

services:
  demo-openresty-config-production:
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-openresty-base-dev
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./naxsi.rules:/usr/local/openresty/nginx/conf/naxsi.rules
    networks:
      - net

