version: "3.1"

services:
  service:
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-zuul-helloworld
    environment:
      - JAVA_OPTS=${java_opts}
      - TZ=Asia/Shanghai
      - eureka_host=${eureka_host}
    restart: unless-stopped
    network_mode: host
