version: "3.1"

services:
  service-account:
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-seata-service-account
    environment:
      - JAVA_OPTS=${java_opts}
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: host
  db-account:
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-seata-db-account
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    restart: unless-stopped
    network_mode: host
