version: "3.0"

services:
  demo-openresty:
    image: openresty/openresty
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"