- name: "启动zuul服务"
  hosts: zuul
  tasks:
    - name: "使用Docker Compose启动zuul服务"
      shell: |
        set -e
        cd ~/deployer-zuul/zuul
        docker compose pull && docker compose up -d

- name: "启动helloworld服务"
  hosts: helloworld
  tasks:
    - name: "使用Docker Compose启动helloworld服务"
      shell: |
        set -e
        cd ~/deployer-zuul/helloworld
        docker compose pull && docker compose up -d

- name: "启动eureka等公共服务"
  hosts: common
  tasks:
    - name: "使用Docker Compose启动eureka等公共服务"
      shell: |
        set -e
        cd ~/deployer-zuul/common
        docker compose pull && docker compose up -d

- name: "启动prometheus公共服务"
  hosts: common
  tasks:
    - name: "使用Docker Compose启动prometheus公共服务"
      shell: |
        set -e
        cd ~/deployer-zuul/prometheus
        docker compose pull && docker compose up -d

- name: "启动OpenResty服务"
  hosts: openresty
  tasks:
    - name: "使用Docker Compose启动OpenResty服务"
      shell: |
        set -e
        cd ~/deployer-zuul/openresty
        docker compose pull && docker compose up -d

- name: "启动node_exporter"
  hosts: "{{ groups['all'] }}"
  tasks:
    - name: "使用Docker Compose启动node_exporter"
      shell: |
        set -e
        cd ~/deployer-zuul/node-exporter
        docker compose up -d
