version: "3.0"

services:
  # 启动mariadb
  db:
    image: mariadb:10.4.19
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
#    ports:
#      - '50000:3306'
    network_mode: host
