spring:
  datasource:
      url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver

# 配置mybatis xml配置文件路径
mybatis:
    mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml